version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/applications/apollo-missions-api
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: deregister_from_elb.sh
      timeout: 180
    - location: scripts/linux/stop_application.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/linux/before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/linux/after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/linux/start_application.sh
      timeout: 300
      runas: ec2-user
    - location: register_with_elb.sh
      timeout: 180
  ValidateService:
    - location: scripts/linux/validate_application.sh
      timeout: 300
      runas: ec2-user
